# Generated by Django 4.1.4 on 2024-02-07 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0002_alter_catalogue_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='seller',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='seller',
            field=models.ForeignKey(db_column='seller', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
