# Generated by Django 4.1.4 on 2024-02-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_categories_alter_catalogue_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mastercatalogue',
            name='category',
        ),
    ]
