# Generated by Django 4.1.4 on 2024-02-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_remove_catalogue_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastercatalogue',
            options={'verbose_name_plural': 'Master Catalogue'},
        ),
        migrations.AddField(
            model_name='catalogue',
            name='category',
            field=models.OneToOneField(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.categories'),
        ),
        migrations.AddField(
            model_name='mastercatalogue',
            name='category',
            field=models.OneToOneField(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.categories'),
        ),
        migrations.AlterModelTable(
            name='mastercatalogue',
            table='master_catalogue',
        ),
    ]
