# Generated by Django 4.1.4 on 2024-02-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_mastercatalogue_options_catalogue_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='mastercatalogue',
            name='product_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='master-images/'),
        ),
        migrations.AlterField(
            model_name='mastercatalogue',
            name='product_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='master-images/'),
        ),
        migrations.AlterField(
            model_name='mastercatalogue',
            name='product_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='master-images/'),
        ),
        migrations.AlterField(
            model_name='mastercatalogue',
            name='product_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='master-images/'),
        ),
        migrations.AlterField(
            model_name='mastercatalogue',
            name='product_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='master-images/'),
        ),
        migrations.AlterModelTable(
            name='categories',
            table='Categories',
        ),
    ]
