# Generated by Django 4.1.4 on 2024-02-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='category',
            field=models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.categories'),
        ),
        migrations.AlterField(
            model_name='mastercatalogue',
            name='category',
            field=models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.categories'),
        ),
    ]
