# Generated by Django 4.1.4 on 2024-02-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_mastercatalogue_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='hsn_code',
            field=models.TextField(),
        ),
    ]
