# Generated by Django 4.2 on 2024-05-25 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('csin', models.CharField(max_length=100)),
                ('ean', models.CharField(max_length=100)),
                ('product_image_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_image_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_image_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_image_4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_image_5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('standardized', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Catalogue',
                'db_table': 'catalogue',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SellerCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn_code', models.TextField()),
                ('quantity', models.CharField(max_length=10)),
                ('seller_sku', models.CharField(max_length=100)),
                ('product_image_6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_image_7', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_image_8', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_image_9', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_image_10', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogue', models.ForeignKey(db_column='catalogue_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.catalogue')),
                ('seller', models.ForeignKey(db_column='seller_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seller Catalogue',
                'db_table': 'seller_catalogue',
            },
        ),
        migrations.CreateModel(
            name='CatalogueTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('catalogues', models.ManyToManyField(related_name='templates', to='catalogue.catalogue')),
            ],
            options={
                'verbose_name_plural': 'Catalogue Templates',
                'db_table': 'catalogue_template',
            },
        ),
        migrations.AddField(
            model_name='catalogue',
            name='category',
            field=models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.categories'),
        ),
    ]
