# Generated by Django 4.2 on 2024-05-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_sellercatalogue_hsn_code_alter_catalogue_csin'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
    ]
